spring.application.name=ecommerce-backend

# Configuração da Base de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/rafaela_shop_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT Configuration
jwt.secret=9a2f8c4e6b0d1e3f5a7c9b2d4e6f8a0c1b3d5e7f9a2b4c6d8e0f1a3b5c7d9e1f
jwt.expiration=86400000